### PR TITLE
Fix for issue #7

### PR DESCRIPTION
**Pull request by neil007m**
Added a new rst file in assets/chapters/english - issue #7

### CODE REVIEW

**Review by alanverdugo — CHANGES_REQUESTED** [review]
Hi @neil007m ! This looks like a great piece of content! However, since it was published in thoughtco.com, I cannot legally include it in the application.

From their terms of use (https://www.thoughtco.com/legal-4801761#terms-of-use):
```
You agree not to modify, reproduce, retransmit, distribute, disseminate, sell, publish, broadcast or circulate any such material without the written permission of ThoughtCo.
```
We could get in legal problems if we share their content without any permissions from thoughtco or the author.

So, we need content that is free to use (the previous chapters are under a permissive license from wikimedia that allows us to use and distribute them).

So either please find a document that has a similar license to those chapters, or even better, you can write some original content yourself and attach an open license to it.

Let me know if you have any questions.

**Comment by neil007m** [comment]
@alanverdugo Sorry about that! I thought it was citable, I'll try to be more thorough in the future.

**Comment by neil007m** [comment]
@alanverdugo this is not ready for review, please bear with me while I figure out how to modify changes made to a pull request

**Comment by alanverdugo** [comment]
No problem @neil007m ,
If you edit the same file, you only need to save it, then
```
git add
git commit
git push
```
It should push the changes and it should reflect them in this pull request.
If you are still having problems after that, you can always close this pull request and open a new one.

**Review by neil007m — COMMENTED** [review]
Modified chapter04.rst

**Comment by neil007m** [comment]
@alanverdugo Thanks so much for assisting! I modified the file and it is ready for review now.

**Review by alanverdugo — APPROVED** [review]
:+1: Awesome!

**Pull request merged**
